# -- Main Menu --
# The main menu is displayed in the header at the top of the page.

[[main]]
  name = "About"
  pageRef = "about"
  weight = 10

[[main]]
  name = "Experience"
  pageRef = "experience"
  weight = 20

[[main]]
  name = "Projects"
  pageRef = "projects"
  weight = 30

[[main]]
  name = "Skills"
  pageRef = "skills"
  weight = 40

[[main]]
  name = "Education"
  pageRef = "education"
  weight = 50

[[main]]
  name = "Blog"
  pageRef = "blog"
  weight = 60

# Social Media Links
[[main]]
  identifier = "linkedin"
  pre = "linkedin"
  url = "https://linkedin.com/in/shivaswaroop-nittoor-krishnamurthy-67551a14b"
  weight = 200

[[main]]
  identifier = "github"
  pre = "github"
  url = "https://github.com/shivaswaroop40"
  weight = 300

[[main]]
  identifier = "email"
  pre = "email"
  url = "mailto:shivaswaroop40@gmail.com"
  weight = 400

# -- Footer Menu --
[[footer]]
  name = "Contact"
  url = "mailto:shivaswaroop40@gmail.com"
  weight = 10
